# Generated by Django 5.1.2 on 2024-11-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания копии')),
                ('content', models.CharField(max_length=255, verbose_name='Содержание копии')),
                ('size', models.PositiveIntegerField(verbose_name='Размер резервной копии (Мб)')),
                ('storage_number', models.CharField(max_length=255, verbose_name='Учетный номер носителя')),
                ('storage_location', models.CharField(max_length=255, verbose_name='Место хранения носителя')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='ФИО, должность лица')),
            ],
            options={
                'verbose_name': 'Запись бэкапа',
                'verbose_name_plural': 'Записи бэкапа',
            },
        ),
    ]
