# Generated by Django 5.1.2 on 2024-11-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuprecord',
            name='created_at',
            field=models.DateField(verbose_name='Дата создания копии'),
        ),
    ]
